# RUPET Pipeline
# The TIA - Team!

trigger:
- master

pool:
  vmImage: windows-latest

jobs:
- job: LoadAgentNode1
  displayName: Rupet1
  continueOnError: true
  workspace:
    clean: outputs
  steps:
    - template: rupet-template.yml

- job: LoadAgentNode2
  displayName: Rupet2
  continueOnError: true
  workspace:
    clean: outputs
  steps:
    - template: rupet-template.yml

