# RUPET Pipeline
# The TIA - Team!

steps:
- script: |
    curl https://api.ipify.org/
  displayName: 'IP info'

- task: Xther-Deployment@0  
  inputs:
    installDir: '$(Build.SourcesDirectory)/xther/'
    resources: 'CHR'
  displayName: 'XTHER install'

- task: PowerShell@2
  inputs:    
    targetType: 'inline'
    script: |
      $destinationFolder = "$(Build.SourcesDirectory)/aimaps_cli/win/selenium/"
      if (!(Test-Path -path $destinationFolder)) {New-Item $destinationFolder -Type Directory}
      Copy-Item '$(Build.SourcesDirectory)/xther/*' $destinationFolder -Force -Recurse
  displayName: 'Install drivers'

- task: PowerShell@2  
  inputs:    
    targetType: 'inline'
    script: |
      dotnet aimaps_cli/win/Gsqa.Tools.AiMaps.Console.dll src='$(Build.SourcesDirectory)/maps/GoogleDemo.aimj'
  displayName: 'Running robots - WIN'